# Generated by Django 2.2.4 on 2019-08-08 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentPortal', '0010_studentinternship_companyname'),
        ('coordinatorPortal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalapplicants',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='finalapplicants',
            name='studentName',
        ),
        migrations.AddField(
            model_name='finalapplicants',
            name='company_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalCompanyName', to='studentPortal.studentInternship'),
        ),
        migrations.AddField(
            model_name='finalapplicants',
            name='student_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalStudentName', to='studentPortal.studentInternship'),
        ),
    ]
