# Generated by Django 2.2.4 on 2019-08-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatorPortal', '0002_auto_20190808_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalapplicants',
            name='company_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finalapplicants',
            name='student_Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
