# Generated by Django 2.2.4 on 2019-08-07 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InternsOnboardMain', '0004_auto_20190806_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentInternship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField(default=False)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InternsOnboardMain.internshipPost')),
                ('studentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
