# Generated by Django 2.2.4 on 2019-08-07 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentPortal', '0002_auto_20190807_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinternship',
            name='studentName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
