# Generated by Django 2.2.4 on 2019-08-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternsOnboardMain', '0004_auto_20190806_1124'),
        ('studentPortal', '0003_studentinternship_studentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinternship',
            name='companyName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InternsOnboardMain.internshipPost'),
        ),
    ]
