# Generated by Django 2.2.4 on 2019-08-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternsOnboardMain', '0004_auto_20190806_1124'),
        ('studentPortal', '0004_studentinternship_companyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentInternshipList',
            fields=[
                ('internshippost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='InternsOnboardMain.internshipPost')),
                ('applied', models.BooleanField(default=False)),
            ],
            bases=('InternsOnboardMain.internshippost',),
        ),
        migrations.DeleteModel(
            name='studentInternship',
        ),
    ]
