# Generated by Django 2.2.4 on 2019-08-08 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentPortal', '0006_auto_20190807_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentInternship',
        ),
    ]
