# Generated by Django 2.2.4 on 2019-08-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentPortal', '0008_studentinternship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinternship',
            name='companyName',
        ),
    ]
