# Generated by Django 2.2.4 on 2019-08-08 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternsOnboardMain', '0006_auto_20190808_0155'),
        ('studentPortal', '0009_remove_studentinternship_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinternship',
            name='companyName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InternsOnboardMain.internshipPost'),
        ),
    ]
