# Generated by Django 2.1.5 on 2019-08-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentPortal', '0010_studentinternship_companyname'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentinternship',
            table='studentInternship',
        ),
    ]
