# Generated by Django 2.1.5 on 2019-08-10 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentPortal', '0011_auto_20190810_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinternship',
            name='companyName',
            field=models.ForeignKey(db_column='companyName', null=True, on_delete=django.db.models.deletion.CASCADE, to='InternsOnboardMain.internshipPost'),
        ),
        migrations.AlterField(
            model_name='studentinternship',
            name='studentName',
            field=models.ForeignKey(db_column='studentName', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
