# Generated by Django 2.2.4 on 2019-08-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InternsOnboardMain', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testPost',
            new_name='internshipPost',
        ),
    ]
