# Generated by Django 2.2.4 on 2019-08-06 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InternsOnboardMain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshippost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='internshippost',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='internshippost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshippost',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinatorName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshippost',
            name='discription',
            field=models.TextField(max_length=1000),
        ),
    ]
