# Generated by Django 2.2.4 on 2019-08-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternsOnboardMain', '0002_auto_20190805_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshippost',
            name='discription',
            field=models.CharField(max_length=500),
        ),
    ]
