# Generated by Django 2.2.4 on 2019-08-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternsOnboardMain', '0003_internshippost_uploader_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshippost',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
