# Generated by Django 2.2.4 on 2019-08-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternsOnboardMain', '0004_auto_20190806_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshippost',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internshippost',
            name='student_name',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
