# Generated by Django 2.2.4 on 2019-08-08 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InternsOnboardMain', '0005_auto_20190808_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshippost',
            name='applied',
        ),
        migrations.RemoveField(
            model_name='internshippost',
            name='student_name',
        ),
    ]
