# Generated by Django 2.2.4 on 2019-08-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InternsOnboardMain', '0006_auto_20190808_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshippost',
            old_name='discription',
            new_name='description',
        ),
    ]
